/* eslint-disable react/no-unescaped-entities */
export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen font-sans">
      <section className="w-full">
        <div className="mx-auto max-w-3xl px-6 py-24 sm:py-32">
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl" style={{ color: "var(--color-rochester-blue)" }}>
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-foreground/60 italic">
            Last updated: October 14, 2025
          </p>

          <p className="mt-6 text-base sm:text-lg leading-7 text-foreground/80">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="mt-4 text-base sm:text-lg leading-7 text-foreground/80">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Interpretation and Definitions
          </h2>
          <h3 className="mt-6 text-xl font-semibold text-foreground">
            Interpretation
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="mt-8 text-xl font-semibold text-foreground">
            Definitions
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            For the purposes of this Privacy Policy:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li><span className="font-semibold">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><span className="font-semibold">Affiliate</span> means an entity that controls, is controlled by, or is under common control with a party.</li>
            <li><span className="font-semibold">Application</span> refers to RocTrades, the software program provided by the Company.</li>
            <li><span className="font-semibold">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to RocTrades.</li>
            <li><span className="font-semibold">Country</span> refers to: New York, United States.</li>
            <li><span className="font-semibold">Device</span> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><span className="font-semibold">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
            <li><span className="font-semibold">Service</span> refers to the Application.</li>
            <li><span className="font-semibold">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><span className="font-semibold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><span className="font-semibold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="mt-6 text-xl font-semibold text-foreground">
            Types of Data Collected
          </h3>
          <h4 className="mt-4 text-lg font-semibold text-foreground">
            Personal Data
          </h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="mt-6 text-lg font-semibold text-foreground">
            Usage Data
          </h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Usage Data is collected automatically when using the Service and may include information such as Your IP address, browser type and version, the pages of our Service that You visit, and other diagnostic data.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
          </p>

          <h3 className="mt-8 text-xl font-semibold text-foreground">
            Information Collected while Using the Application
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li>Pictures and other information from your Device's camera and photo library</li>
          </ul>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            You can enable or disable access to this information at any time, through Your Device settings.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Use of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li><span className="font-semibold">To provide and maintain our Service</span>, including to monitor the usage of our Service.</li>
            <li><span className="font-semibold">To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><span className="font-semibold">For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><span className="font-semibold">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><span className="font-semibold">To provide You</span> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
            <li><span className="font-semibold">To manage Your requests:</span> To attend and manage Your requests to Us.</li>
            <li><span className="font-semibold">For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
            <li><span className="font-semibold">For other purposes</span>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
          </ul>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We may share Your personal information in the following situations:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li><span className="font-semibold">With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li><span className="font-semibold">For business transfers:</span> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
            <li><span className="font-semibold">With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
            <li><span className="font-semibold">With business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
            <li><span className="font-semibold">With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
            <li><span className="font-semibold">With Your consent</span>: We may disclose Your personal information for any other purpose with Your consent.</li>
          </ul>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Retention of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy and as required to comply with legal obligations, resolve disputes, and enforce our agreements and policies.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Transfer of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Delete Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Our Service may give You the ability to delete certain information about You from within the Service.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Disclosure of Your Personal Data
          </h3>
          <h4 className="mt-4 text-lg font-semibold text-foreground">Business Transactions</h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>
          <h4 className="mt-6 text-lg font-semibold text-foreground">Law enforcement</h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>
          <h4 className="mt-6 text-lg font-semibold text-foreground">Other legal requirements</h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Security of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We strive to use commercially reasonable means to protect Your Personal Data, but no method of transmission over the Internet or electronic storage is 100% secure.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Children's Privacy
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Links to Other Websites
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Changes to this Privacy Policy
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Contact Us
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li>By email: <a href="mailto:contact@roctrades.com" className="underline">contact@roctrades.com</a></li>
            <li>By phone: 5859575354</li>
          </ul>
        </div>
      </section>
    </main>
  );
}


