export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen font-sans">
      <section className="w-full">
        <div className="mx-auto max-w-3xl px-6 py-24 sm:py-32">
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl" style={{ color: "var(--color-rochester-blue)" }}>
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-foreground/60 italic">
            Last updated: October 14, 2025
          </p>

          <p className="mt-6 text-base sm:text-lg leading-7 text-foreground/80">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="mt-4 text-base sm:text-lg leading-7 text-foreground/80">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Interpretation and Definitions
          </h2>
          <h3 className="mt-6 text-xl font-semibold text-foreground">
            Interpretation
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="mt-8 text-xl font-semibold text-foreground">
            Definitions
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            For the purposes of this Privacy Policy:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li><span className="font-semibold">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><span className="font-semibold">Affiliate</span> means an entity that controls, is controlled by, or is under common control with a party.</li>
            <li><span className="font-semibold">Application</span> refers to RocTrades, the software program provided by the Company.</li>
            <li><span className="font-semibold">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to RocTrades.</li>
            <li><span className="font-semibold">Country</span> refers to: New York, United States.</li>
            <li><span className="font-semibold">Device</span> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><span className="font-semibold">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
            <li><span className="font-semibold">Service</span> refers to the Application.</li>
            <li><span className="font-semibold">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><span className="font-semibold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><span className="font-semibold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="mt-6 text-xl font-semibold text-foreground">
            Types of Data Collected
          </h3>
          <h4 className="mt-4 text-lg font-semibold text-foreground">
            Personal Data
          </h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="mt-3 list-disc pl-6 text-base leading-7 text-foreground/80">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="mt-6 text-lg font-semibold text-foreground">
            Usage Data
          </h4>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Usage Data is collected automatically when using the Service and may include information such as Your IP address, browser type and version, the pages of our Service that You visit, and other diagnostic data.
          </p>

          <h3 className="mt-8 text-xl font-semibold text-foreground">
            Information Collected while Using the Application
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission, pictures and other information from your Device's camera and photo library.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Use of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company may use Personal Data for purposes including to provide and maintain our Service, manage Your Account, perform contracts, contact You, provide You with information, manage Your requests, conduct business transfers, and for other purposes such as data analysis and improving our Service.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Retention of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy and as required to comply with legal obligations, resolve disputes, and enforce our agreements and policies.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Transfer of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Your information may be transferred to and maintained on computers located outside of Your jurisdiction where the data protection laws may differ from those from Your jurisdiction.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Delete Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You, subject to certain legal obligations.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Disclosure of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We may disclose Your Personal Data under certain circumstances such as business transactions, law enforcement requests, or other legal requirements.
          </p>

          <h3 className="mt-10 text-xl font-semibold text-foreground">
            Security of Your Personal Data
          </h3>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We strive to use commercially reasonable means to protect Your Personal Data, but no method of transmission over the Internet or electronic storage is 100% secure.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Children's Privacy
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Our Service does not address anyone under the age of 13. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Links to Other Websites
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Changes to this Privacy Policy
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-foreground">
            Contact Us
          </h2>
          <p className="mt-2 text-base leading-7 text-foreground/80">
            If you have any questions about this Privacy Policy, You can contact us at <a href="mailto:contact@roctrades.com" className="underline">contact@roctrades.com</a>.
          </p>
        </div>
      </section>
    </main>
  );
}


